/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moremote.p2p_ITCPRelayLibrary */

#ifndef _Included_moremote.p2p_ITCPRelayLibrary
#define _Included_moremote.p2p_ITCPRelayLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moremote.p2p_ITCPRelayLibrary
 * Method:    connectToRelayServer
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_moremote.p2p_ITCPRelayLibrary_connectToRelayServer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     moremote.p2p_ITCPRelayLibrary
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moremote.p2p_ITCPRelayLibrary_close
  (JNIEnv *, jobject);

/*
 * Class:     moremote.p2p_ITCPRelayLibrary
 * Method:    auth
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_moremote.p2p_ITCPRelayLibrary_auth
  (JNIEnv *, jobject, jboolean, jstring, jstring);

/*
 * Class:     moremote.p2p_ITCPRelayLibrary
 * Method:    sendMessage
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_moremote.p2p_ITCPRelayLibrary_sendMessage
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
